### ISSUE TITLE
[Welcome] Check listener

### ISSUE THREAD

**Issue by Injabie3** [SFUAnime/Ren#233]
Blip in one join not being logged. Check console at earliest convenience

**Comment by Injabie3** [comment]
Been consistently happening for the last two weeks or so.
```
[09/08/2019 21:53] ERROR welcome sendWelcomeMessage 87: Could not send message, make sure the server has a title and message set!
[09/08/2019 21:53] ERROR welcome sendWelcomeMessage 89: FORBIDDEN (status code: 403): Cannot send messages to this user
Ignoring exception in member_join
Traceback (most recent call last):
  File "/home/ren/github/Ren/cogs/welcome.py", line 85, in sendWelcomeMessage
    await self.bot.send_message(newUser, embed=welcomeEmbed)
  File "red.py", line 98, in send_message
    return await super().send_message(*args, **kwargs)
  File "lib/discord/client.py", line 1151, in send_message
    data = yield from self.http.send_message(channel_id, content, guild_id=guild_id, tts=tts, embed=embed)
  File "lib/discord/http.py", line 196, in request
    raise Forbidden(r, data)
discord.errors.Forbidden: FORBIDDEN (status code: 403): Cannot send messages to this user

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "lib/discord/ext/commands/bot.py", line 252, in _run_extra
    yield from coro(*args, **kwargs)
  File "/home/ren/github/Ren/cogs/welcome.py", line 96, in sendWelcomeMessage
    newUser))
AttributeError: 'Member' object has no attribute 'descriminator'
```
Looks like a spelling error somewhere within d.py, but have to investigate further.

**Comment by Injabie3** [comment]
DMs turned off, need to handle this case.
