### ISSUE TITLE
[Heist] NoneType

### ISSUE THREAD

**Issue by Injabie3** [SFUAnime/Ren#25]
Error on 11 people.
```bash
[02/06/2017 15:54] ERROR red on_command_error 369: Exception in command 'heist play'
Traceback (most recent call last):
  File "lib/discord/ext/commands/core.py", line 50, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "/home/ren/github/Ren/cogs/heist.py", line 115, in _play_heist
    await self.heist_game(settings, server)
  File "/home/ren/github/Ren/cogs/heist.py", line 129, in heist_game
    outcomes = self.game_outcomes(settings)
  File "/home/ren/github/Ren/cogs/heist.py", line 503, in game_outcomes
    if randint(0, 100) <= chance:
TypeError: unorderable types: int() <= NoneType()
[02/06/2017 16:00] ERROR red on_command_error 369: Exception in command 'heist play'
Traceback (most recent call last):
  File "lib/discord/ext/commands/core.py", line 50, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "/home/ren/github/Ren/cogs/heist.py", line 115, in _play_heist
    await self.heist_game(settings, server)
  File "/home/ren/github/Ren/cogs/heist.py", line 129, in heist_game
    outcomes = self.game_outcomes(settings)
  File "/home/ren/github/Ren/cogs/heist.py", line 503, in game_outcomes
    if randint(0, 100) <= chance:
TypeError: unorderable types: int() <= NoneType()
```

**Comment by Injabie3** [comment]
Patched a few weeks ago with update 0c58b42c332a419cc245dc7b4970a9926ce786c3.
