### ISSUE TITLE
[Filter] Handling exceptions

### ISSUE THREAD

**Issue by Injabie3** [SFUAnime/Ren#32]
```
Traceback (most recent call last):
  File "lib/discord/ext/commands/bot.py", line 252, in _run_extra
    yield from coro(*args, **kwargs)
  File "/home/ubuntu/github/Ren/cogs/word_filter.py", line 198, in check_words
    filtered_msg = self._filter_word(word,filtered_msg)
  File "/home/ubuntu/github/Ren/cogs/word_filter.py", line 220, in _filter_word
    return re.sub(regex,repl,string,flags=re.IGNORECASE)
  File "/usr/lib/python3.5/re.py", line 182, in sub
    return _compile(pattern, flags).sub(repl, string, count)
  File "/usr/lib/python3.5/re.py", line 293, in _compile
    p = sre_compile.compile(pattern, flags)
  File "/usr/lib/python3.5/sre_compile.py", line 536, in compile
    p = sre_parse.parse(p, flags)
  File "/usr/lib/python3.5/sre_parse.py", line 829, in parse
    p = _parse_sub(source, pattern, 0)
  File "/usr/lib/python3.5/sre_parse.py", line 437, in _parse_sub
    itemsappend(_parse(source, state))
  File "/usr/lib/python3.5/sre_parse.py", line 641, in _parse
    source.tell() - here + len(this))
sre_constants.error: multiple repeat at position 9
```

**Comment by Injabie3** [comment]
Added try, except code block near line 198, have yet to push changes up.
