### ISSUE TITLE
RSS Fail Possibly after `asyncio.wait`

### ISSUE THREAD

**Issue by KamiCreed** [SFUAnime/Ren#37]
### Type:

- [ ] Suggestion
- [X] Bug

### Actual behavior

That `SmartReact update...` part is doing an `asyncio.wait(1200)`.

```
SmartReact update wait started for Server Injabie3 - Staging
------------------------------------
RSS: scanning feed(s) for updates...
------------------------------------
RSS: no new items in feed 0
RSS: 1 new items in feed 1
RSS: no new items in feed 2
exception calling callback for <Future at 0x7f72d4b20c50 state=finished returned list>
Traceback (most recent call last):
  File "/usr/lib/python3.5/concurrent/futures/_base.py", line 297, in _invoke_callbacks
    callback(self)
  File "/usr/lib/python3.5/asyncio/futures.py", line 442, in _call_set_state
    dest_loop.call_soon_threadsafe(_set_state, destination, source)
  File "/usr/lib/python3.5/asyncio/base_events.py", line 532, in call_soon_threadsafe
    handle = self._call_soon(callback, args)
  File "/usr/lib/python3.5/asyncio/base_events.py", line 506, in _call_soon
    self._check_closed()
  File "/usr/lib/python3.5/asyncio/base_events.py", line 334, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
exception calling callback for <Future at 0x7f72e368a668 state=finished returned list>
Traceback (most recent call last):
  File "/usr/lib/python3.5/concurrent/futures/_base.py", line 297, in _invoke_callbacks
    callback(self)
  File "/usr/lib/python3.5/asyncio/futures.py", line 442, in _call_set_state
    dest_loop.call_soon_threadsafe(_set_state, destination, source)
  File "/usr/lib/python3.5/asyncio/base_events.py", line 532, in call_soon_threadsafe
    handle = self._call_soon(callback, args)
  File "/usr/lib/python3.5/asyncio/base_events.py", line 506, in _call_soon
    self._check_closed()
  File "/usr/lib/python3.5/asyncio/base_events.py", line 334, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
Task was destroyed but it is pending!
task: <Task pending coro=<RSSFeed._rss() running at /home/ren/github/TestServer/cogs/rss.py:181> wait_for=<Future pending cb=[_chain_future.<locals>._call_check_cancel() at /usr/lib/python3.5/asyncio/futures.py:431, Task._wakeup()]>>
Task was destroyed but it is pending!
task: <Task pending coro=<Streams.stream_checker() running at /home/ren/github/TestServer/cogs/streams.py:584> wait_for=<Future pending cb=[_chain_future.<locals>._call_check_cancel() at /usr/lib/python3.5/asyncio/futures.py:431, Task._w
akeup()]>>
```

After this, the bot restarts.

### Steps to reproduce

Haven't tried to reproduce. Just dumping the stack trace for now.

1. 
2. 
3. 
4.

**Comment by Injabie3** [comment]
Going to have to debug this later, since it's showing up in `prod-aws`, but I don't have any logs there :'(

**Comment by Injabie3** [comment]
Some console debugging:
```sh
Task exception was never retrieved
future: <Task finished coro=<RSSFeed._rss_loop() done, defined at /home/ubuntu/github/Ren/cogs/rss.py:154> exception=TimeoutError()>
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/tasks.py", line 241, in _step
    result = coro.throw(exc)
  File "/home/ubuntu/github/Ren/cogs/rss.py", line 183, in _rss_loop
    page = await resp.text()
  File "lib/aiohttp/client_reqrep.py", line 764, in text
    yield from self.read()
  File "lib/aiohttp/client_reqrep.py", line 739, in read
    self._content = yield from self.content.read()
  File "lib/aiohttp/streams.py", line 518, in wrapper
    result = yield from func(self, *args, **kw)
  File "lib/aiohttp/streams.py", line 583, in read
    return (yield from super().read(n))
  File "lib/aiohttp/streams.py", line 290, in read
    block = yield from self.readany()
  File "lib/aiohttp/streams.py", line 518, in wrapper
    result = yield from func(self, *args, **kw)
  File "lib/aiohttp/streams.py", line 593, in readany
    return (yield from super().readany())
  File "lib/aiohttp/streams.py", line 307, in readany
    yield from self._wait('readany')
  File "lib/aiohttp/streams.py", line 224, in _wait
    yield from waiter
  File "/usr/lib/python3.5/asyncio/futures.py", line 361, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.5/asyncio/tasks.py", line 296, in _wakeup
    future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
concurrent.futures._base.TimeoutError
```

**Comment by Injabie3** [comment]
Bot no longer is dying here, closing.
