### ISSUE TITLE
Renslots error

### ISSUE THREAD

**Issue by KamiCreed** [SFUAnime/Ren#40]
## Type:

- [ ] Suggestion
- [X] Bug - low priority

An exception on renslot maybe? Nothing major happened, so probably Ok. Maybe Ren just got interrupted doing something else. If so, then that probably should be handled better.

**Says "Exception in command 'slot'"**

Not sure what happened, so just dumping log:

```bash
SmartReact Error:
FORBIDDEN (status code: 403): Missing Permissions
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f1a6ffe5d68>
Server Leave  : User Stella#1316 (240040828951592960) has left the server.
Server Welcome: User Stella#1316 (240040828951592960) has joined.  DM sent.
Ignoring exception in message
Traceback (most recent call last):
  File "lib/aiohttp/client_reqrep.py", line 640, in start
    message = yield from httpstream.read()
  File "lib/aiohttp/streams.py", line 641, in read
    result = yield from super().read()
  File "lib/aiohttp/streams.py", line 476, in read
    yield from self._waiter
  File "/usr/lib/python3.5/asyncio/futures.py", line 361, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.5/asyncio/tasks.py", line 296, in _wakeup
    future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 266, in result
    raise CancelledError
concurrent.futures._base.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "lib/discord/ext/commands/bot.py", line 252, in _run_extra
    yield from coro(*args, **kwargs)
  File "/home/ren/github/Ren/cogs/highlight.py", line 242, in check_highlights
    active = await self._is_active(user['id'],msg.channel,msg)
  File "/home/ren/github/Ren/cogs/highlight.py", line 279, in _is_active
    async for msg in self.bot.logs_from(channel,limit=50,before=message):
  File "lib/discord/iterators.py", line 173, in __anext__
    msg = yield from self.iterate()
  File "lib/discord/iterators.py", line 115, in iterate
    yield from self.fill_messages()
  File "lib/discord/iterators.py", line 123, in fill_messages
    data = yield from self._retrieve_messages(retrieve)
  File "lib/discord/iterators.py", line 141, in _retrieve_messages_before_strategy
    data = yield from self.client._logs_from(self.channel, retrieve, before=self.before)
  File "lib/discord/http.py", line 137, in request
    r = yield from self.session.request(method, url, **kwargs)
  File "lib/aiohttp/client.py", line 555, in __iter__
    resp = yield from self._coro
  File "lib/aiohttp/client.py", line 202, in _request
    yield from resp.start(conn, read_until_eof)
  File "lib/aiohttp/client_reqrep.py", line 640, in start
    message = yield from httpstream.read()
  File "lib/async_timeout/__init__.py", line 35, in __exit__
    self._do_exit(exc_type)
  File "lib/async_timeout/__init__.py", line 80, in _do_exit
    raise asyncio.TimeoutError
concurrent.futures._base.TimeoutError
Ignoring exception in message
Traceback (most recent call last):
  File "lib/discord/ext/commands/bot.py", line 252, in _run_extra
    yield from coro(*args, **kwargs)
  File "/home/ren/github/Ren/cogs/highlight.py", line 242, in check_highlights
    active = await self._is_active(user['id'],msg.channel,msg)
  File "/home/ren/github/Ren/cogs/highlight.py", line 279, in _is_active
    async for msg in self.bot.logs_from(channel,limit=50,before=message):
  File "lib/discord/iterators.py", line 173, in __anext__
    msg = yield from self.iterate()
  File "lib/discord/iterators.py", line 115, in iterate
    yield from self.fill_messages()
  File "lib/discord/iterators.py", line 123, in fill_messages
    data = yield from self._retrieve_messages(retrieve)
  File "lib/discord/iterators.py", line 141, in _retrieve_messages_before_strategy
    data = yield from self.client._logs_from(self.channel, retrieve, before=self.before)
  File "lib/discord/http.py", line 200, in request
    raise HTTPException(r, data)
discord.errors.HTTPException: INTERNAL SERVER ERROR (status code: 500): 500: Internal Server Error
Ignoring exception in message
Traceback (most recent call last):
  File "lib/discord/ext/commands/bot.py", line 252, in _run_extra
    yield from coro(*args, **kwargs)
  File "/home/ren/github/Ren/cogs/highlight.py", line 242, in check_highlights
    active = await self._is_active(user['id'],msg.channel,msg)
  File "/home/ren/github/Ren/cogs/highlight.py", line 279, in _is_active
    async for msg in self.bot.logs_from(channel,limit=50,before=message):
  File "lib/discord/iterators.py", line 173, in __anext__
    msg = yield from self.iterate()
  File "lib/discord/iterators.py", line 115, in iterate
    yield from self.fill_messages()
  File "lib/discord/iterators.py", line 123, in fill_messages
    data = yield from self._retrieve_messages(retrieve)
  File "lib/discord/iterators.py", line 141, in _retrieve_messages_before_strategy
    data = yield from self.client._logs_from(self.channel, retrieve, before=self.before)
  File "lib/discord/http.py", line 200, in request
    raise HTTPException(r, data)
discord.errors.HTTPException: INTERNAL SERVER ERROR (status code: 500): 500: Internal Server Error
Ignoring exception in message
Traceback (most recent call last):
  File "lib/discord/ext/commands/bot.py", line 252, in _run_extra
    yield from coro(*args, **kwargs)
  File "/home/ren/github/Ren/cogs/highlight.py", line 242, in check_highlights
    active = await self._is_active(user['id'],msg.channel,msg)
  File "/home/ren/github/Ren/cogs/highlight.py", line 279, in _is_active
    async for msg in self.bot.logs_from(channel,limit=50,before=message):
  File "lib/discord/iterators.py", line 173, in __anext__
    msg = yield from self.iterate()
  File "lib/discord/iterators.py", line 115, in iterate
    yield from self.fill_messages()
  File "lib/discord/iterators.py", line 123, in fill_messages
    data = yield from self._retrieve_messages(retrieve)
  File "lib/discord/iterators.py", line 141, in _retrieve_messages_before_strategy
    data = yield from self.client._logs_from(self.channel, retrieve, before=self.before)
  File "lib/discord/http.py", line 200, in request
    raise HTTPException(r, data)
discord.errors.HTTPException: INTERNAL SERVER ERROR (status code: 500): 500: Internal Server Error
Ignoring exception in message
Traceback (most recent call last):
  File "lib/discord/ext/commands/bot.py", line 252, in _run_extra
    yield from coro(*args, **kwargs)
  File "/home/ren/github/Ren/cogs/highlight.py", line 242, in check_highlights
    active = await self._is_active(user['id'],msg.channel,msg)
  File "/home/ren/github/Ren/cogs/highlight.py", line 279, in _is_active
    async for msg in self.bot.logs_from(channel,limit=50,before=message):
  File "lib/discord/iterators.py", line 173, in __anext__
    msg = yield from self.iterate()
  File "lib/discord/iterators.py", line 115, in iterate
    yield from self.fill_messages()
  File "lib/discord/iterators.py", line 123, in fill_messages
    data = yield from self._retrieve_messages(retrieve)
  File "lib/discord/iterators.py", line 141, in _retrieve_messages_before_strategy
    data = yield from self.client._logs_from(self.channel, retrieve, before=self.before)
  File "lib/discord/http.py", line 200, in request
    raise HTTPException(r, data)
discord.errors.HTTPException: INTERNAL SERVER ERROR (status code: 500): 500: Internal Server Error
[11/01/2018 00:27] ERROR red on_command_error 369: Exception in command 'slot'
Traceback (most recent call last):
  File "lib/discord/ext/commands/core.py", line 50, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "/home/ren/github/Ren/cogs/economy.py", line 550, in slot
    await self.slot_machine(author, bid)
  File "/home/ren/github/Ren/cogs/economy.py", line 614, in slot_machine
    "".format(slot, author.mention, bid, then, now))
  File "lib/discord/ext/commands/bot.py", line 309, in _augmented_msg
    msg = yield from coro
  File "/home/ren/github/Ren/cogs/lolz.py", line 121, in predicate
    msg = await old_send(destination, content, *args, **kwargs)
  File "red.py", line 92, in send_message
    return await super().send_message(*args, **kwargs)
  File "lib/discord/client.py", line 1151, in send_message
    data = yield from self.http.send_message(channel_id, content, guild_id=guild_id, tts=tts, embed=embed)
  File "lib/discord/http.py", line 200, in request
    raise HTTPException(r, data)
discord.errors.HTTPException: INTERNAL SERVER ERROR (status code: 500): 500: Internal Server Error
Ignoring exception in message
Traceback (most recent call last):
  File "lib/discord/ext/commands/bot.py", line 252, in _run_extra
    yield from coro(*args, **kwargs)
  File "/home/ren/github/Ren/cogs/highlight.py", line 242, in check_highlights
    active = await self._is_active(user['id'],msg.channel,msg)
  File "/home/ren/github/Ren/cogs/highlight.py", line 279, in _is_active
    async for msg in self.bot.logs_from(channel,limit=50,before=message):
  File "lib/discord/iterators.py", line 173, in __anext__
    msg = yield from self.iterate()
  File "lib/discord/iterators.py", line 115, in iterate
    yield from self.fill_messages()
  File "lib/discord/iterators.py", line 123, in fill_messages
    data = yield from self._retrieve_messages(retrieve)
  File "lib/discord/iterators.py", line 141, in _retrieve_messages_before_strategy
    data = yield from self.client._logs_from(self.channel, retrieve, before=self.before)
  File "lib/discord/http.py", line 200, in request
    raise HTTPException(r, data)
discord.errors.HTTPException: INTERNAL SERVER ERROR (status code: 500): 500: Internal Server Error
[11/01/2018 00:27] ERROR red on_command_error 369: Exception in command 'slot'
Traceback (most recent call last):
  File "lib/discord/ext/commands/core.py", line 50, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "/home/ren/github/Ren/cogs/economy.py", line 550, in slot
    await self.slot_machine(author, bid)
  File "/home/ren/github/Ren/cogs/economy.py", line 614, in slot_machine
    "".format(slot, author.mention, bid, then, now))
  File "lib/discord/ext/commands/bot.py", line 309, in _augmented_msg
    msg = yield from coro
  File "/home/ren/github/Ren/cogs/lolz.py", line 121, in predicate
    msg = await old_send(destination, content, *args, **kwargs)
  File "red.py", line 92, in send_message
    return await super().send_message(*args, **kwargs)
  File "lib/discord/client.py", line 1151, in send_message
    data = yield from self.http.send_message(channel_id, content, guild_id=guild_id, tts=tts, embed=embed)
  File "lib/discord/http.py", line 200, in request
    raise HTTPException(r, data)
discord.errors.HTTPException: INTERNAL SERVER ERROR (status code: 500): 500: Internal Server Error
```

**Comment by Injabie3** [comment]
Well, it seems like a bunch of gateway errors, probably due to a timeout or something when going through to a Discord server.  Closing for now.
