### ISSUE TITLE
[Highlight] sre_constants error

### ISSUE THREAD

**Issue by Injabie3** [SFUAnime/Ren#45]
Please be sure to read through other issues as well to make sure what you are suggesting/reporting has not already
been suggested/reported

### Type:

- [ ] Suggestion
- [x] Bug

### Brief description of the problem
See below log. Investigate later.
```bash
Ignoring exception in message
Traceback (most recent call last):
  File "lib/discord/ext/commands/bot.py", line 252, in _run_extra
    yield from coro(*args, **kwargs)
  File "/home/ren/github/Ren/cogs/highlight.py", line 243, in check_highlights
    match = self._is_word_match(word,msg.content)
  File "/home/ren/github/Ren/cogs/highlight.py", line 274, in _is_word_match
    return bool(re.search(regex,string.lower()))
  File "/usr/lib/python3.5/re.py", line 173, in search
    return _compile(pattern, flags).search(string)
  File "/usr/lib/python3.5/re.py", line 293, in _compile
    p = sre_compile.compile(pattern, flags)
  File "/usr/lib/python3.5/sre_compile.py", line 536, in compile
    p = sre_parse.parse(p, flags)
  File "/usr/lib/python3.5/sre_parse.py", line 829, in parse
    p = _parse_sub(source, pattern, 0)
  File "/usr/lib/python3.5/sre_parse.py", line 437, in _parse_sub
    itemsappend(_parse(source, state))
  File "/usr/lib/python3.5/sre_parse.py", line 638, in _parse
    source.tell() - here + len(this))
sre_constants.error: nothing to repeat at position 2
```
### Expected behavior
n/a
### Actual behavior
n/a
### Steps to reproduce

1. Send a message in any text channel.

**Comment by Injabie3** [comment]
Identified the trigger word causing the issue:
`+pat <@123123123123>` (ID obscured)

**Comment by Injabie3** [comment]
Good explanation of the problem here https://stackoverflow.com/questions/3675144/regex-error-nothing-to-repeat

**Comment by Injabie3** [comment]
lmao
```
In #general-chat, you were mentioned with highlight word ?t:
Injabie3
[22:21:30 PST] Toyona#0056: wao candy
[22:21:34 PST] Toyona#0056: pls do share
[22:21:51 PST] Toyona#0056: (if its shareable)
[22:25:42 PST] Toyona#0056: https://youtu.be/0I90MuvoYQM?t=1m25s
Triggered at | Tue, 06 Mar 2018 10:25PM PST
```

**Comment by Injabie3** [comment]
Reopen if this still occurs in new version.
