### ISSUE TITLE
[AfterHours] `makeStarboardChanges` references `starboard` before assignment

### ISSUE THREAD

**Issue by quachtridat** [SFUAnime/Ren#458]
## Bug
In `starboard.py`,
```py
def makeStarboardChanges(self, ctx: Context, channel: discord.abc.GuildChannel, remove=False):
        # ...
        try:
            starboard = sbCog.starboards[ctx.guild.id]["highlights"]
        except KeyError:
            self.logger.error("Cannot get the starboard!")

        if remove:
            await ctx.invoke(sbCog.blacklist_remove, starboard=starboard, channel_or_role=channel)
        else:
            await ctx.invoke(sbCog.blacklist_add, starboard=starboard, channel_or_role=channel)
```
The `starboard` instance passed to `starboard` argument on invocation of `ctx.invoke()` fails when its preceding `try/except` block fails to obtain a `starboard` instance from `sbCog`.

## Log
```log
Ignoring exception in on_guild_channel_create
Traceback (most recent call last):
  File "e:\data\coding\git\repos\sfu\ren\.venv\lib\site-packages\discord\client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "E:\Data\Coding\Git\Repos\SFU\Ren\cogs\afterhours\afterhours.py", line 300, in handleChannelCreate
    await self.makeStarboardChanges(ctx, channel)
  File "E:\Data\Coding\Git\Repos\SFU\Ren\cogs\afterhours\afterhours.py", line 251, in makeStarboardChanges
    await ctx.invoke(sbCog.blacklist_add, starboard=starboard, channel_or_role=channel)
UnboundLocalError: local variable 'starboard' referenced before assignment
```

## Reproduction
1. Make sure there is no `highlights` channel.
2. Load `starboard`.
3. Load `afterhours`.
4. Create an `after-hours` channel.

**Comment by quachtridat** [comment]
## Possible fix
```py
def makeStarboardChanges(self, ctx: Context, channel: discord.abc.GuildChannel, remove=False):
        # ...
        try:
            starboard = sbCog.starboards[ctx.guild.id]["highlights"]
            if remove:
                await ctx.invoke(sbCog.blacklist_remove, starboard=starboard, channel_or_role=channel)
            else:
                await ctx.invoke(sbCog.blacklist_add, starboard=starboard, channel_or_role=channel)
        except KeyError:
            self.logger.error("Cannot get the starboard!")
```
This way, `starboard` is available for `ctx.invoke` calls to reference.
