### ISSUE TITLE
[Birthday] Crashing on daily sweep

### ISSUE THREAD

**Issue by KamiCreed** [SFUAnime/Ren#46]
### Type:

- [ ] Suggestion
- [X] Bug

### Brief description of the problem

Possibly caused the crash of the bot and server.

```
Make sure to keep your bot updated. Select the 'Update' option from the launcher.
[WARNING:] -- Overwriting bot.send_message with send_lolz. If bot.send_message is not reloaded,
[WARNING:] -- in the event of a crash of the lolz cog, you may not be able revert to bot.send_message without a restart/reloading lolz
SmartReact Error:
FORBIDDEN (status code: 403): Missing Permissions
Ignoring exception in message
Traceback (most recent call last):
  File "lib/aiohttp/client_reqrep.py", line 640, in start
    message = yield from httpstream.read()
  File "lib/aiohttp/streams.py", line 641, in read
    result = yield from super().read()
  File "lib/aiohttp/streams.py", line 476, in read
    yield from self._waiter
  File "/usr/lib/python3.5/asyncio/futures.py", line 361, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.5/asyncio/tasks.py", line 296, in _wakeup
    future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 266, in result
    raise CancelledError
concurrent.futures._base.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "lib/discord/ext/commands/bot.py", line 252, in _run_extra
    yield from coro(*args, **kwargs)
  File "/home/ren/github/Ren/cogs/highlight.py", line 242, in check_highlights
    active = await self._is_active(user['id'],msg.channel,msg)
  File "/home/ren/github/Ren/cogs/highlight.py", line 283, in _is_active
    async for msg in self.bot.logs_from(channel,limit=50,before=message):
  File "lib/discord/iterators.py", line 173, in __anext__
    msg = yield from self.iterate()
  File "lib/discord/iterators.py", line 115, in iterate
    yield from self.fill_messages()
  File "lib/discord/iterators.py", line 123, in fill_messages
    data = yield from self._retrieve_messages(retrieve)
  File "lib/discord/iterators.py", line 141, in _retrieve_messages_before_strategy
    data = yield from self.client._logs_from(self.channel, retrieve, before=self.before)
  File "lib/discord/http.py", line 137, in request
    r = yield from self.session.request(method, url, **kwargs)
  File "lib/aiohttp/client.py", line 555, in __iter__
    resp = yield from self._coro
  File "lib/aiohttp/client.py", line 202, in _request
    yield from resp.start(conn, read_until_eof)
  File "lib/aiohttp/client_reqrep.py", line 640, in start
    message = yield from httpstream.read()
  File "lib/async_timeout/__init__.py", line 35, in __exit__
    self._do_exit(exc_type)
  File "lib/async_timeout/__init__.py", line 80, in _do_exit
    raise asyncio.TimeoutError
concurrent.futures._base.TimeoutError
Server Leave  : User Selaznog#5902 (173514211857661952) has left the server.
```

**Comment by Injabie3** [comment]
Could also be from highlights cog, cause I wrapped a bunch of stuff in `try`, `except` for SmartReact when we first had `#dark-hour` to suppress the Discord exceptions from no perms.

**Comment by Injabie3** [comment]
Lmao
`'NoneType' object has no attribute 'roles'`

Edit:
Okay that was normal.

**Comment by Injabie3** [comment]
Added some debug code, but something is happening with the `await` that is causing it to hang, but no exception is thrown.

**Comment by Injabie3** [comment]
Hmm, there was something hidden I'm guessing...checked out `birthday.py` to most recent comment and we're back to normal.
