### ISSUE TITLE
[Highlight] Notify fails because of AttributeError

### ISSUE THREAD

**Issue by Injabie3** [SFUAnime/Ren#499]
Figure out how this is happening:
```
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/ubuntu/github/renchan/lib/python3.8/site-packages/discord.py-1.7.3-py3.8.egg/discord/client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "/home/ubuntu/github/renchan/Ren/cogs/highlight/highlight.py", line 765, in onMessage
    await self.checkHighlights(msg)
  File "/home/ubuntu/github/renchan/Ren/cogs/highlight/highlight.py", line 702, in checkHighlights
    await asyncio.gather(*tasks)  # pylint: disable=no-member
  File "/home/ubuntu/github/renchan/Ren/cogs/highlight/highlight.py", line 719, in _notifyUser
    "In #{1.channel.name}, you were mentioned with highlight word "
AttributeError: 'Object' object has no attribute 'name'
```

**Comment by quachtridat** [comment]
It's a documented case.
https://github.com/Rapptz/discord.py/issues/21#issuecomment-151697291
https://github.com/Rapptz/discord.py/blob/master/discord/object.py#L53-L56

**Comment by Injabie3** [comment]
c/wf
