### ISSUE TITLE
[Heist] Results Error

### ISSUE THREAD

**Issue by KamiCreed** [SFUAnime/Ren#52]
### Type:

- [ ] Suggestion
- [x] Bug

### Brief description of the problem

Some exception happened when showing the results of a `renheist`.

### Expected behavior

Show the results of `renheist`.

### Actual behavior

![image](https://user-images.githubusercontent.com/9517086/39415901-381ed2b2-4bfd-11e8-8989-86ce13938875.png)

```
discord.errors.HTTPException: INTERNAL SERVER ERROR (status code: 500): 500: Internal Server Error
[29/04/2018 22:27] ERROR red on_command_error 369: Exception in command 'heist play'
Traceback (most recent call last):
  File "lib/discord/ext/commands/core.py", line 50, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "/home/ren/github/Ren/cogs/heist.py", line 514, in _play_heist
    await self.heist_game(settings, server, t_heist, t_crew, t_vault)
  File "/home/ren/github/Ren/cogs/heist.py", line 732, in heist_game
    await self.show_results(settings, results)
  File "/home/ren/github/Ren/cogs/heist.py", line 697, in show_results
    await self.bot.say(result)
  File "lib/discord/ext/commands/bot.py", line 309, in _augmented_msg
    msg = yield from coro
  File "red.py", line 92, in send_message
    return await super().send_message(*args, **kwargs)
  File "lib/discord/client.py", line 1151, in send_message
    data = yield from self.http.send_message(channel_id, content, guild_id=guild_id, tts=tts, embed=embed)
  File "lib/discord/http.py", line 200, in request
    raise HTTPException(r, data)
discord.errors.HTTPException: INTERNAL SERVER ERROR (status code: 500): 500: Internal Server Error
Ignoring exception in message
Traceback (most recent call last):
  File "lib/discord/ext/commands/bot.py", line 252, in _run_extra
    yield from coro(*args, **kwargs)
  File "/home/ren/github/Ren/cogs/highlight.py", line 242, in check_highlights
    active = await self._is_active(user['id'],msg.channel,msg)
  File "/home/ren/github/Ren/cogs/highlight.py", line 283, in _is_active
    async for msg in self.bot.logs_from(channel,limit=50,before=message):
  File "lib/discord/iterators.py", line 173, in __anext__
    msg = yield from self.iterate()
  File "lib/discord/iterators.py", line 115, in iterate
    yield from self.fill_messages()
  File "lib/discord/iterators.py", line 123, in fill_messages
    data = yield from self._retrieve_messages(retrieve)
  File "lib/discord/iterators.py", line 141, in _retrieve_messages_before_strategy
    data = yield from self.client._logs_from(self.channel, retrieve, before=self.before)
  File "lib/discord/http.py", line 200, in request
    raise HTTPException(r, data)
```

**Comment by KamiCreed** [comment]
Might just be a temporary error due to not being able to send an HTTP request?

**Comment by Injabie3** [comment]
I'm leaning towards that, since it just seems like it's an unhandled exception.

**Comment by Injabie3** [comment]
Closing, no new info to be had at this moment.
