### ISSUE TITLE
[Tags] Fix `[p]tag settings dump` command

### ISSUE THREAD

**Issue by Injabie3** [SFUAnime/Ren#587]
Command is erroring out, should root cause and fix it.

**Comment by quachtridat** [comment]
Traceback log:
```
Traceback (most recent call last):
  File "$REN_VENV_PATH/lib/python3.8/site-packages/$DISCORD_PKG/discord/ext/commands/core.py", line 85, in wrapped
    ret = await coro(*args, **kwargs)
  File "$REN_PATH/cogs/tags/tags.py", line 368, in dump
    with open(DUMP_IN, "r") as inputFile, open(DUMP_OUT, "w") as outputFile:
FileNotFoundError: [Errno 2] No such file or directory: 'data/tags/tags.json'
```
Looks like we need to reconfigure the path to the JSON file.
