### ISSUE TITLE
Permissions error in heist

### ISSUE THREAD

**Issue by KamiCreed** [SFUAnime/Ren#62]
### Type:

- [ ] Suggestion
- [X] Bug

### Expected behavior

Heist working properly.

### Actual behavior

![image](https://user-images.githubusercontent.com/9517086/42132001-9c7dae08-7cc3-11e8-9de5-11ef42f93aa0.png)

```
    data = yield from self.http.send_message(channel_id, content, guild_id=guild_id, tts=tts, embed=embed)
  File "lib/discord/http.py", line 196, in request
    raise Forbidden(r, data)
discord.errors.Forbidden: FORBIDDEN (status code: 403): Missing Permissions
[30/06/2018 22:41] ERROR red on_command_error 369: Exception in command 'heist play'
Traceback (most recent call last):
  File "lib/discord/ext/commands/core.py", line 50, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "/home/ren/github/Ren/cogs/heist.py", line 506, in _play_heist
    "{3}.".format(author.name, wait_time, ctx.prefix, t_crew, t_heist))
  File "lib/discord/ext/commands/bot.py", line 309, in _augmented_msg
    msg = yield from coro
  File "red.py", line 92, in send_message
    return await super().send_message(*args, **kwargs)
  File "lib/discord/client.py", line 1151, in send_message
    data = yield from self.http.send_message(channel_id, content, guild_id=guild_id, tts=tts, embed=embed)
  File "lib/discord/http.py", line 196, in request
    raise Forbidden(r, data)
discord.errors.Forbidden: FORBIDDEN (status code: 403): Missing Permissions
Ignoring exception in on_command_error
Traceback (most recent call last):
  File "lib/discord/client.py", line 307, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "red.py", line 378, in on_command_error
    await ctx.bot.send_message(channel, inline(message))
  File "red.py", line 92, in send_message
    return await super().send_message(*args, **kwargs)
```

### Steps to reproduce

`renheist play`

**Comment by KamiCreed** [comment]
`renheist reset`
