### ISSUE TITLE
[SFU] MaxRetryError isn't caught, use ConnectionError instead

### ISSUE THREAD

**Issue by Injabie3** [SFUAnime/Ren#663]
In the latest run, retries failed so we expected MaxRetryError to be caught. Instead, it wasn't and we got a traceback like this:
```
ren  | [2024-05-05 18:05:08] [WARNING] urllib3.connectionpool: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectionResetError(104, 'Connection reset by peer')': /public/images/aqn-current.jpg?nocache=1&update=15000&timeout=1800000
ren  | [2024-05-05 18:05:08] [WARNING] urllib3.connectionpool: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectionResetError(104, 'Connection reset by peer')': /public/images/aqn-current.jpg?nocache=1&update=15000&timeout=1800000
ren  | [2024-05-05 18:05:09] [WARNING] urllib3.connectionpool: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectionResetError(104, 'Connection reset by peer')': /public/images/aqn-current.jpg?nocache=1&update=15000&timeout=1800000
ren  | [2024-05-05 18:05:12] [WARNING] urllib3.connectionpool: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectionResetError(104, 'Connection reset by peer')': /public/images/aqn-current.jpg?nocache=1&update=15000&timeout=1800000
ren  | [2024-05-05 18:05:16] [WARNING] urllib3.connectionpool: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectionResetError(104, 'Connection reset by peer')': /public/images/aqn-current.jpg?nocache=1&update=15000&timeout=1800000
ren  | [2024-05-05 18:05:16] [ERROR] red: Exception in command 'sfu cam'
ren  | urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
ren  | 
ren  | The above exception was the direct cause of the following exception:
ren  | 
ren  | Traceback (most recent call last):
ren  |   File "/data/venv/lib/python3.11/site-packages/requests/adapters.py", line 486, in send
ren  |     resp = conn.urlopen(
ren  |            ^^^^^^^^^^^^^
ren  |   File "/data/venv/lib/python3.11/site-packages/urllib3/connectionpool.py", line 874, in urlopen
ren  |     return self.urlopen(
ren  |            ^^^^^^^^^^^^^
ren  |   File "/data/venv/lib/python3.11/site-packages/urllib3/connectionpool.py", line 874, in urlopen
ren  |     return self.urlopen(
ren  |            ^^^^^^^^^^^^^
ren  |   File "/data/venv/lib/python3.11/site-packages/urllib3/connectionpool.py", line 874, in urlopen
ren  |     return self.urlopen(
ren  |            ^^^^^^^^^^^^^
ren  |   [Previous line repeated 2 more times]
ren  |   File "/data/venv/lib/python3.11/site-packages/urllib3/connectionpool.py", line 844, in urlopen
ren  |     retries = retries.increment(
ren  |               ^^^^^^^^^^^^^^^^^^
ren  |   File "/data/venv/lib/python3.11/site-packages/urllib3/util/retry.py", line 515, in increment
ren  |     raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
ren  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ren  | urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='ns-webcams.its.sfu.ca', port=80): Max retries exceeded with url: /public/images/aqn-current.jpg?nocache=1&update=15000&timeout=1800000 (Caused by ProtocolError('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer')))
ren  | 
ren  | During handling of the above exception, another exception occurred:
ren  | 
ren  | Traceback (most recent call last):
ren  |   File "/data/venv/lib/python3.11/site-packages/discord/ext/commands/core.py", line 235, in wrapped
ren  |     ret = await coro(*args, **kwargs)
ren  |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
ren  |   File "/data/cogs/CogManager/cogs/sfu/roads.py", line 131, in cam
ren  |     fetchedData = self.httpRetrySession.get(camera, headers=self.headers)
ren  |                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ren  |   File "/data/venv/lib/python3.11/site-packages/requests/sessions.py", line 602, in get
ren  |     return self.request("GET", url, **kwargs)
ren  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ren  |   File "/data/venv/lib/python3.11/site-packages/requests/sessions.py", line 589, in request
ren  |     resp = self.send(prep, **send_kwargs)
ren  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ren  |   File "/data/venv/lib/python3.11/site-packages/requests/sessions.py", line 703, in send
ren  |     r = adapter.send(request, **kwargs)
ren  |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ren  |   File "/data/venv/lib/python3.11/site-packages/requests/adapters.py", line 519, in send
ren  |     raise ConnectionError(e, request=request)
ren  | requests.exceptions.ConnectionError: HTTPConnectionPool(host='ns-webcams.its.sfu.ca', port=80): Max retries exceeded with url: /public/images/aqn-current.jpg?nocache=1&update=15000&timeout=1800000 (Caused by ProtocolError('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer')))
```

It actually doesn't hit the MaxRetryError block. What we should do here is handle the `ConnectionError` exception instead.

**Comment by Injabie3** [comment]
Fixed in #664, closing.
